### ISSUE TITLE
NapChat使用有如下问题。

### ISSUE THREAD

**Issue by M1hono** [I-linmeng-I/YGOAssistant#9]
2024-09-25 15:28:09 W/Onebot: Request failed: [send_group_forward_msg] app=NapCat.Onebot v2.6.14, message=Error: 转发消息失败，生成节点为空
    at GoCQHTTPSendGroupForwardMsg.handleForwardedNodes (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36795:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GoCQHTTPSendGroupForwardMsg._handle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36694:26)
    at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36606:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:12791:21), retJson={"status":"failed","retcode":1200,"data":null,"message":"Error: 转发消息失败，生成节点 为空\n    at GoCQHTTPSendGroupForwardMsg.handleForwardedNodes (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36795:39)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GoCQHTTPSendGroupForwardMsg._handle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36694:26)\n    at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36606:23)\n    at async OB11ActiveWebSocketAdapter.handleMessage (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:12791:21)","wording":"Error: 转发消息失败，生成节点为空\n    at GoCQHTTPSendGroupForwardMsg.handleForwardedNodes (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36795:39)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GoCQHTTPSendGroupForwardMsg._handle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36694:26)\n    at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:36606:23)\n    at async OB11ActiveWebSocketAdapter.handleMessage (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:12791:21)","echo":6}

**Comment by I-linmeng-I** [comment]
貌似不是我这插件的问题？能描述一下出bug的场景嘛
